# Specify version format
version: "G+Smo-stable.{build}"

# Operating system (build VM template)
os: 
#  - Windows Server 2012 R2
#  - Default Azure
#  - SharePoint 2013
#  - MinGW
#  - Visual Studio 2014 CTP4
  - Visual Studio 2015

#clone_depth: 5 # clone entire repository history if not defined
shallow_clone: true

# scripts that are called at very beginning, before repo cloning
#init:
#  - cmd: cmake --version
#  - cmd: echo Platform is %platform%
#  - cmd: set
#  - cmd: msbuild /version
#  - cmd: wmic os get osarchitecture

# clone directory
clone_folder: C:\projects\gismo

# branches to build
branches:
  only:
    - stable

# Do not build on tags (GitHub only)
skip_tags: true

# scripts that run after cloning repository
install:
  # install mingw
  #- if [%BUILD%]==[mingw] appveyor DownloadFile "https://bintray.com/artifact/download/drewwells/generic/x86_64-4.9.2-release-win32-seh-rt_v4-rev3.7z" -FileName mw64.7z
  - if [%BUILD%]==[mingw] appveyor DownloadFile "http://netcologne.dl.sourceforge.net/project/mingw-w64/Toolchains targetting Win64/Personal Builds/mingw-builds/5.1.0/threads-win32/seh/x86_64-5.1.0-release-win32-seh-rt_v4-rev0.7z" -FileName mw64.7z
  #- if [%BUILD%]==[mingw] appveyor DownloadFile "http://netcologne.dl.sourceforge.net/project/mingw-w64/Toolchains targetting Win64/Personal Builds/mingw-builds/5.1.0/threads-posix/seh/x86_64-5.1.0-release-posix-seh-rt_v4-rev0.7z" -FileName mw64.7z
  - if [%BUILD%]==[mingw] 7z x -oC:\ mw64.7z > NUL

# scripts to run before build
before_build:
  - if [%BUILD%]==[msvc2015] set envpath=C:\Program Files (x86)\MSBuild\14.0\Bin
  #- if [%BUILD%]==[mingw] set PATH=C:\mingw64\bin;%PATH%
  #- if [%BUILD%]==[mingw] rename "C:\Program Files (x86)\Git\bin\sh.exe" "sh2.exe"
  - if [%BUILD%]==[mingw] rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
  - cmd: cd C:\projects	&& md build-gismo && cd build-gismo
  - set PATH=%envpath%;%PATH%
  - cmd: cmake -DSITE="AppVeyor.com" -DBUILDNAME="%generator% %configuration%" -G "%generator%" -DCMAKE_BUILD_TYPE=%configuration% -DGISMO_WITH_ONURBS=ON -DGISMO_BUILD_UNITTESTS=ON ../gismo

# for MSYS
#  - cmd: C:\MinGW\msys\1.0\bin\sh --login -c "
#    echo 'C:\MinGW\ /MinGW' > /etc/fstab;
#    cd /c/projects/build-gismo;
#    cmake -G'MSYS Makefiles'  ../gismo;
#    make -j2 Experimental
#    "

build_script:
  #- cmd: if (%BUILD%=="mingw") (mingw32-make -j4) else (msbuild /m:4 /p:Configuration=%configuration% /verbosity:minimal C:\projects\build-gismo\gismo.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll")
  - cmd: ctest -j5 -C %configuration% -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalSubmit #-V

#build:
#  project: C:\projects\build-gismo\gismo.sln
#  parallel: true # enable MSBuild parallel builds
#  verbosity: minimal # MSBuild verbosity level (quiet|minimal|normal|detailed)
# NuGet
#publish_nuget: true
#publish_nuget_symbols: true
#include_nuget_references: true
#test_script:
#- cmd: ctest -j2 -D ExperimentalMemCheck


##############################################################
for:

# Stable branch
-
  branches:
    only:
    - stable

  environment:
    CTEST_OUTPUT_ON_FAILURE: 1
    matrix:
    - BUILD: msvc2015
      configuration: Release
      generator: "Visual Studio 14 2015"


# Full tests
-
  branches:
    only:
    - coverity_scan

  environment:
    # custom environment variables, see http://www.appveyor.com/docs/installed-software
    CTEST_OUTPUT_ON_FAILURE: 1
    #BOOST_ROOT: c:\Libraries\boost
    #BOOST_LIBRARYDIR: c:\Libraries\boost\stage\lib
    matrix:
    - BUILD: msvc2015
      configuration: Release
      generator: "Visual Studio 14 2015"

    - BUILD: msvc2015
      configuration: Release
      generator: "Visual Studio 14 2015 Win64"

    - BUILD: msvc2015
      configuration: Debug
      generator: "Visual Studio 14 2015 Win64"

    - BUILD: mingw
      envpath: C:\mingw64\bin
      configuration: Release 
      generator: "MinGW Makefiles"
      #MSYS Makefiles

    - BUILD: msvc2013
      configuration: Release
      generator: "Visual Studio 12"

    - BUILD: msvc2012
      configuration: Release
      generator: "Visual Studio 11"

    - BUILD: msvc2010
      configuration: Release
      generator: "Visual Studio 10"

#  - BUILD: msvc2008
#  Note:  error C2039: 'data' : is not a member of 'std::vector<_Ty>' 
#  ( &std::vector<_Ty>::front() would work)
#    configuration: Release
#    generator: "Visual Studio 9 2008"

#configuration:
#  - Debug
#  - RelWithDebInfo
#  - Release

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
#platform: 
#  - Win32
#  - x64

#artifacts:
#  - path: tt
#    name: ipopt
#    type: dll

#validate: https://codebeautify.org/yaml-validator
